# Namespace config
namespace:
  # Name space where you want to run the cert-updater BatchJob
  name: f5-certs
  # Labels of the namespace
  labels: {}
service_account:
  # Name of the service account
  name: f5-certs-sa
role:
  # Name of the role running the cert job
  name: f5-certs-role

# Configuration of the BatchJob
certUpdater:
  # How often the BatchJob should run
  crontabExpression: 0 8 * * *
  # Loglevel of the job
  logLevel: DEBUG
  # Which image to use. You can either use the one below,
  # or build your own with the Dockerfile in this repo
  image: bigipreport/f5-k8s-certs:v0.0.1
  # When should the image be pulled?
  imagePullPolicy: Always
