apiVersion: batch/v1
kind: CronJob
metadata:
  name: cert-updater
  namespace: {{ .Values.namespace.name  }}
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 10
  schedule: {{ .Values.certUpdater.crontabExpression}}
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: cert-updater
            image: {{ .Values.certUpdater.image }}
            imagePullPolicy: {{ .Values.certUpdater.imagePullPolicy }}
            env:
            - name: NAMESPACE
              value: {{ .Values.namespace.name  }}
            - name: LOGLEVEL
              value: {{ .Values.certUpdater.logLevel  }}
          restartPolicy: Never
          serviceAccountName: f5-certs-sa
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            fsGroup: 472
