---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: f5-certs-role
  namespace: {{ .Values.namespace  }}
rules:          # Authorization rules for this role
  - apiGroups:  # 1st API group
      - ''      # An empty string designates the core API group.
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - cert-manager.io
    resources:
      - certificates
    verbs:
      - list
      - get
