apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: f5-certs-rolebinding
  namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.role.name }}
subjects:
- namespace: {{ .Values.namespace.name }}
  kind: ServiceAccount
  name: {{ .Values.service_account.name }}
